---

# Main tasks file for lizmap role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::lizmap'
    - 'role::lizmap::config'
    - 'role::lizmap::init'
    - 'role::lizmap::install'

- name: 'INIT | Ensure lizmap_persistant_crypt_key is not empty'
  assert:
    that: "lizmap_persistant_crypt_key | length > 0"
    msg: "'lizmap_persistant_crypt_key' must not be an empty string"
  tags:
    - 'role::lizmap'
    - 'role::lizmap::config'
    - 'role::lizmap::init'
    - 'role::lizmap::install'


- name: 'INSTALL | Manage OS family installation tasks'
  include_tasks: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::lizmap'
    - 'role::lizmap::install'


- name: 'INSTALL | Manage Lizmap common pre-installation tasks'
  include_tasks: "{{ role_path }}/tasks/common_pre_install.yml"
  tags:
    - 'role::lizmap'
    - 'role::lizmap::install'


- name: 'INSTALL | ZIP | Manage Lizmap installation tasks'
  include_tasks: "{{ role_path }}/tasks/install_from_zip.yml"
  when: "lizmap_install_method == 'zip'"
  tags:
    - 'role::lizmap'
    - 'role::lizmap::install'
