---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "lizmap-docker-debian9"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:9'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "lizmap-docker-debian10"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:10'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "lizmap-docker-ubuntu18"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:18.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "lizmap-docker-ubuntu20"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:20.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
  inventory:
    group_vars:
      all:
        lizmap_install_demo_repositories: False
        lizmap_persistant_crypt_key: '922584ef8185a91ae85a521d7d92e278'
        __php_modules_enabled:
          - 'curl'
          - 'dom'
          - 'gd'
          - 'pdo_sqlite'
          - 'simplexml'
          - 'sqlite3'
          - 'wddx'
          - 'xml'
          - 'xmlreader'
          - 'xmlrpc'
          - 'xmlwriter'
          - 'xsl'
        php_modules_enabled: "{{ _php_modules_enabled + __php_modules_enabled }}"
        php_dependencies_services: []
        php_packages:
          - name: "php{{ _php_version }}-cgi"
          - name: "php{{ _php_version }}-gd"
          - name: "php{{ _php_version }}-sqlite3"
          - name: "php{{ _php_version }}-curl"
          - name: "php{{ _php_version }}-xml"
          - name: "php{{ _php_version }}-xmlrpc"
scenario:
  name: 'default'
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  options:
    sudo: True
