---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "lizmap-docker-xenial"
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        lizmap_install_demo_repositories: False
        lizmap_persistant_crypt_key: '922584ef8185a91ae85a521d7d92e278'
        php_packages:
          - name: 'php7.0-cgi'
          - name: 'php7.0-gd'
          - name: 'php7.0-sqlite3'
          - name: 'php7.0-curl'
          - name: 'php7.0-xml'
          - name: 'php7.0-xmlrpc'
        __php_modules_enabled:
          - 'curl'
          - 'dom'
          - 'gd'
          - 'pdo_sqlite'
          - 'simplexml'
          - 'sqlite3'
          - 'wddx'
          - 'xml'
          - 'xmlreader'
          - 'xmlrpc'
          - 'xmlwriter'
          - 'xsl'
        php_modules_enabled: "{{ _php_modules_enabled + __php_modules_enabled }}"
        php_dependencies_services: []
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
